### ISSUE TITLE
OpenET API availability and access

### ISSUE THREAD

**Issue by dataspun** [Open-ET/openet-core-beta#17]
The OpenET newsroom has been quiet for over a year, with the exception of one blog post. The official [website](https://openetdata.org/api/) still says:

> OpenET plans to launch an Application Programming Interface (API) in **early 2022**. 

When will the API launch, and is it still possible to gain beta access?

Thanks!

**Comment by cgmorton** [comment]
I would suggest using the "Contact Us" link found on that same site to get more information about API access.
